builds:
  - main: cmd/amonagent.go
    binary: amonagent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
fpm:
  homepage:  http://goreleaser.github.io
  description: Amon Monitoring Agent
  maintainer: Martin Rusev <martin@amon.cx>
  license: MIT
  vendor: Amon
  formats:
    - deb
    - rpm
  dependencies:
    - sysstat

snapshot:
  name_template: SNAPSHOT-{{.Commit}}